### ISSUE TITLE
access 403

### ISSUE THREAD

**Issue by sathish1981** [ozh/yourls-fallback-url#1]
@ozh 
When I updated a url without protocol like www.errorpage.com in config settings. And tried to type a keyword which is not in DB. Then the pagee redirects to root domain like http://short.me/blah redirects to http://short.me

Also, if we mention the url with protocol like https or http://www.errorpage.com, and try to save the config which is forwarded to 403 error.

Let me know if i trying the option correctly. Also is there a way i can place a file called error.php or error.html in the same yourls folder and mention in the config file?

**Comment by ozh** [comment]
Hello

Sorry, I don't understand what you're explaining :-/
