### ISSUE TITLE
This plug-in no longer works

### ISSUE THREAD

**Issue by CharlesMagnuson** [ozh/yourls-fallback-url#3]
I've had version 1.0 of this plug-in installed and working for a very long time, but just today it dawned on me that I had configured a fallback URL but it's no longer working. I suspect this has something to do with http://diegopeinador.com/ dying.

Is there any chance you could release a new, working version of this plug-in?

**Comment by ozh** [comment]
I've merged a PR (that was submitting a year ago... sorry :)
Other than this I'm not maintaining this plugin, merely providing a mirror
